use core::sync::atomic::{AtomicU32, AtomicUsize, Ordering};
use field_oriented::{RotorFeedback, RotorFeedbackFault};
use crate::capture;

// MULTISINE_HARMONICS and MULTISINE_TABLE generated by build.rs
include!(concat!(env!("OUT_DIR"), "/multisine_table.rs"));

/// Bias current as a fraction of the rated current limit
const BIAS_FRACTION: f32 = 0.5;
/// Excitation amplitude as a fraction of the rated current limit
const EXCITATION_FRACTION: f32 = 0.4;

const STATE_IDLE: u32 = 0;
const STATE_ARMED: u32 = 1;
const STATE_ALIGN: u32 = 2;
const STATE_RUNNING: u32 = 3;

static STATE: AtomicU32 = AtomicU32::new(STATE_IDLE);
static TICK: AtomicUsize = AtomicUsize::new(0);

/// Arms the test to start on the next FOC tick with a live torque setpoint and a known torque constant,
/// it runs until the debug capture buffer is full.
pub fn arm() {
    STATE.store(STATE_ARMED, Ordering::Release);
}

const FAKE_ALIGN_FEEDBACK: RotorFeedback = RotorFeedback {angle_type: field_oriented::AngleType::Electrical, theta: -1.57079632679, omega: 0.0};
const FAKE_TEST_FEEDBACK: RotorFeedback = RotorFeedback {angle_type: field_oriented::AngleType::Electrical, theta: 0.0, omega: 0.0};

/// Replaces the torque setpoint with the biased multisine excitation while the test is running.
pub fn multisine_torque(target_torque: Option<f32>, rotor_feedback: Result<RotorFeedback, RotorFeedbackFault>, rated_current_limit_a: f32, torque_constant: Option<f32>) -> (Option<f32>, Result<RotorFeedback, RotorFeedbackFault>) {
    let (Some(_), Some(kt)) = (target_torque, torque_constant) else {
        if STATE.load(Ordering::Acquire) == STATE_RUNNING {
            STATE.store(STATE_IDLE, Ordering::Release);
        }
        return (target_torque, rotor_feedback);
    };
    match STATE.load(Ordering::Acquire) {
        STATE_ARMED => {
            TICK.store(0, Ordering::Relaxed);
            STATE.store(STATE_ALIGN, Ordering::Release);
            return (target_torque, rotor_feedback);
        }
        STATE_ALIGN => {
            let tick = TICK.load(Ordering::Relaxed);
            if tick > 100_000 {
                if tick > 200_000 {
                    TICK.store(0, Ordering::Relaxed);
                    capture::start();
                    STATE.store(STATE_RUNNING, Ordering::Release);
                } else {
                    TICK.store(tick + 1, Ordering::Relaxed);
                }
                return (Some(0.0), Ok(FAKE_ALIGN_FEEDBACK));
            } else {
                TICK.store(tick + 1, Ordering::Relaxed);
                return (Some(0.5*rated_current_limit_a*kt), Ok(FAKE_ALIGN_FEEDBACK));
            }
        }
        STATE_RUNNING => {
            let tick = TICK.load(Ordering::Relaxed);
            TICK.store(tick + 1, Ordering::Relaxed);
            let current_a = rated_current_limit_a * (BIAS_FRACTION + EXCITATION_FRACTION * MULTISINE_TABLE[tick % MULTISINE_TABLE.len()]);
            return (Some(current_a * kt), Ok(FAKE_TEST_FEEDBACK))
        }
        _ => return (target_torque, rotor_feedback),
    }
}

/// Called on the tick that fills the capture buffer, returns true if that ended a running test.
pub fn finish() -> bool {
    if STATE.load(Ordering::Acquire) != STATE_RUNNING {
        return false;
    }
    STATE.store(STATE_IDLE, Ordering::Release);
    true
}
