use core::sync::atomic::{AtomicU32, AtomicUsize, Ordering};

use crate::capture;

// MULTISINE_HARMONICS and MULTISINE_TABLE generated by build.rs
include!(concat!(env!("OUT_DIR"), "/multisine_table.rs"));

/// Excitation amplitude as a fraction of the rated current limit
const EXCITATION_CURRENT_FRACTION: f32 = 0.5;

const STATE_IDLE: u32 = 0;
const STATE_ARMED: u32 = 1;
const STATE_RUNNING: u32 = 2;

static STATE: AtomicU32 = AtomicU32::new(STATE_IDLE);
static TICK: AtomicUsize = AtomicUsize::new(0);

/// Arms the test to start on the next FOC tick with a live torque setpoint and a known torque constant,
/// it runs until the debug capture buffer is full.
pub fn arm() {
    STATE.store(STATE_ARMED, Ordering::Release);
}

/// Superimposes the multisine excitation on the torque setpoint while the test is running.
pub fn multisine_torque(target_torque: Option<f32>, rated_current_limit_a: f32, torque_constant: Option<f32>) -> Option<f32> {
    let (Some(torque), Some(kt)) = (target_torque, torque_constant) else {
        if STATE.load(Ordering::Acquire) == STATE_RUNNING {
            STATE.store(STATE_IDLE, Ordering::Release);
        }
        return target_torque;
    };
    match STATE.load(Ordering::Acquire) {
        STATE_ARMED => {
            TICK.store(0, Ordering::Relaxed);
            capture::start();
            STATE.store(STATE_RUNNING, Ordering::Release);
        }
        STATE_RUNNING => {}
        _ => return target_torque,
    }
    let tick = TICK.load(Ordering::Relaxed);
    TICK.store(tick + 1, Ordering::Relaxed);
    let amplitude_nm = EXCITATION_CURRENT_FRACTION * rated_current_limit_a * kt;
    Some(torque + amplitude_nm * MULTISINE_TABLE[tick % MULTISINE_TABLE.len()])
}

/// Called on the tick that fills the capture buffer, returns true if that ended a running test.
pub fn finish() -> bool {
    if STATE.load(Ordering::Acquire) != STATE_RUNNING {
        return false;
    }
    STATE.store(STATE_IDLE, Ordering::Release);
    true
}
