[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "probe-rs run"
rustflags = ["-C", "target-cpu=cortex-m4"]

[build]
target = "thumbv7em-none-eabihf"

[env]
DEFMT_RTT_BUFFER_SIZE = "4096"