[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "probe-rs run"
rustflags = ["-C", "target-cpu=cortex-m4"]

[build]
target = "thumbv7em-none-eabihf"

[alias]
rb = "run --bin"
rrb = "run --release --bin"
bbr = "build --release --bin"
