[package]
name = "servo_firmware"
edition = "2021"
version = "0.0.1"

[features]
default = ["board-zest1"]
mcu-opamps = []
hall-feedback = []
spi-encoder = []
overcurrent-comparators = []
board-zest1 = ["mcu-opamps", "hall-feedback", "spi-encoder", "overcurrent-comparators"]

[dependencies]
cortex-m = { version = "0.7", features = ["critical-section-single-core"] }
defmt = { version = "1", features = ["encoding-rzcobs"] }
panic-probe = { version = "1", features = ["print-defmt"] }
rtic = { version = "2.0.0", features = ["thumbv7-backend"] }
rtic-monotonics = { version = "1.5", default-features = false, features = ["stm32g473qe", "stm32_tim2"] }
embassy-stm32 = { path = "../embassy/embassy-stm32", features = ["stm32g473qe", "defmt", "memory-x", "unstable-pac", "exti", "dual-bank"] }
embedded-can = "0.4"
firmware-core = { path = "../firmware-core" }
field-oriented = { path = "../field-oriented" }
defmt-rtt = "1.1.0"
libm = "0.2"
bitvec = { version = "1", default-features = false }
serde = { version = "1", default-features = false, features = ["derive"] }

[build-dependencies]
dbc-codegen = "0.3"
can-dbc = "5.0"
heck = "0.5"

[profile.dev]
codegen-units = 1
debug = 2
debug-assertions = true
incremental = false
opt-level = "s"
overflow-checks = true

[profile.release]
codegen-units = 1
debug = 2
debug-assertions = false
incremental = false
lto = 'fat'
opt-level = 3
overflow-checks = false
